version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Backend/CleanArchitecture.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CleanArchitectureDb;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;
    networks:
      - CleanArchitecture-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - CleanArchitecture-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - CleanArchitecture-network
    restart: always

volumes:
  sqlserver-data:

networks:
  CleanArchitecture-network:
